name: Sync Fork

on:
  push:
  schedule:
    - cron: '*/60 * * * *'
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: coolsnowwolf
          head: master
          base: master
